variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

pool:
  name: "Self-hosted scale set - Ubuntu 20.04"

steps:
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '$(MAVEN_OPTS)'
    goals: 'spring-boot:run'
    publishJUnitResults: false